### ISSUE TITLE
Is this exporter tested for concurrent workflow executions?

### ISSUE THREAD

**Issue by amitonlentra** [camunda-community-hub/zeebe-redis-exporter#129]
We are using zeebe 8.2.12. We plan to use this exporter to fetch incident details at runtime and also for monitoring/troubleshooting workflow executions. 

While going through the code, I came across [instance variables declared](https://github.com/camunda-community-hub/zeebe-redis-exporter/blob/e134e7fd15de0a11d610bc783a6e2bc7e3eeeb4f/exporter/src/main/java/io/zeebe/redis/exporter/RedisExporter.java#L37) in the exporter class. I wanted to ask if the exporter would work when there are concurrent workflow executions running. 

Thanks

**Comment by amitonlentra** [comment]
Thanks @VonDerBeck for the comments. We recently tried the clickhouse-exporter and it failed during concurrent process executions, hence I posted this just to double check.

On digging further, I see that this repo also includes code for reading the data from redis-streams which is used by zeebe-simple-monitor. We plan to use zeebe-simple-monitor too in our application deployment. 
In the reader code ([ZeebeRedis](https://github.com/camunda-community-hub/zeebe-redis-exporter/blob/e134e7fd15de0a11d610bc783a6e2bc7e3eeeb4f/connector-java/src/main/java/io/zeebe/redis/connect/java/ZeebeRedis.java#L160)) I also see that the reading is done in a single thread. 

I am new to redis but we have observed scalability issues with zeebe-hazelcast-exporter which does the same thing hence wanted to understand if you see scalability issues in reading events from redis streams when there are huge number of records exported to redis from zeebe.

**Comment by VonDerBeck** [comment]
Hi @amitonlentra,

you wrote: "In the reader code I also see that the reading is done in a single thread." 

That statement is half true and half false and - as of version 0.9.11 - depends on whether you are connecting to a Redis Cluster or not.

Reading from streams is done in [ZeebeRedis.readNext()](https://github.com/camunda-community-hub/zeebe-redis-exporter/blob/e134e7fd15de0a11d610bc783a6e2bc7e3eeeb4f/connector-java/src/main/java/io/zeebe/redis/connect/java/ZeebeRedis.java#L254).

Please read [Using Redis Clusters](https://github.com/camunda-community-hub/zeebe-redis-exporter?tab=readme-ov-file#using-redis-clusters) for a deeper understanding.

In short:
- when **not** using a Redis cluster the connector uses a blocking Multi-key operation to receive events from Redis. This is indeed done in a single thread taking care of all streams at once.
- when using a Redis cluster the connector uses multiple connections to read from each stream individually based on the asynchronous connection pool support of Lettuce (the underlying Redis client) - leading to multiple threads, one for each stream.

What's currently not implemented is the optional use of the asynchronous connection pool support of Lettuce in case you do not use a cluster. This could be something to implement in the future. Before doing so I would be interested if the current options are sufficient for your scenario or not.

Performance on the event receiver side - in my opinion - is way more dependent on how fast the receiver is able to process the incoming events (and you're right, multiple threads might help with that). In case of Zeebe Simple Monitor the question is, how fast events can be stored in the database. The main problem with the Hazelcast exporter is that it uses a Ringbuffer! In case of high load combined with slow event receivers this could lead to scenarios where not yet processed events will be overwritten by new ones. Even if like the Hazelcast exporter very much this is nothing I would risk in production. The good thing is that this will not happen with Redis streams.

So just give a start and let me know how this behaves in your environment.

Regards
Gunnar

**Comment by amitonlentra** [comment]
Thanks @VonDerBeck for the valuable insights.

> Before doing so I would be interested if the current options are sufficient for your scenario or not.

Yes this is sufficient. In our scenario we would be deploying a redis cluster through helm. So effectively `RedisClusterClient` would be executed behind the scenes

> The main problem with the Hazelcast exporter is that it uses a Ringbuffer! In case of high load combined with slow event receivers this could lead to scenarios where not yet processed events will be overwritten by new ones.

You have accurately captured the essence. We experienced the same issues when executing a load test with hazelcast and zeeqs. We are hoping we don't face that with redis and zeebe-simple-monitor.

> Performance on the event receiver side - in my opinion - is way more dependent on how fast the receiver is able to process the incoming events (and you're right, multiple threads might help with that). In case of Zeebe Simple Monitor the question is, how fast events can be stored in the database. 

When going through the zeebe-simple-monitor code I see the application just registers listeners to the `RedisConnectionBuilder` class of redis-connector for different record types. The listener code then executes create/update operations as necessary. So since the redis stream is read concurrently in a batch form by the connector, I am hoping that the listeners do get called concurrently for different record types.
