### ISSUE TITLE
Process Variables Not Returned in UserTaskRecord

### ISSUE THREAD

**Issue by asalhani** [camunda-community-hub/zeebe-redis-exporter#203]
I've successfully set up the exporter according to the provided guide. The exporter has been enabled in the Camunda 8 Docker Compose core version (excluding Optimize and Identity).

I developed a small Spring Boot application to consume the exported records from the Redis stream. I was able to activate the listener related to the user task, named addUserTaskListener. However, I observed that the process variables are not being returned with the UserTaskRecord. The variables_ field and getVariables() method always return an empty string ("").

To ensure the process has at least one variable, I verified it within the Tasklist app. Additionally, I tested a simple gateway in the process, which successfully read the variable's value and acted upon it, confirming that the variable is recognized and respected by the Zeebe engine during runtime.

Below are some screenshot that will highlight to you the issue I descriped above:

This is how I'm initiating a new process with var:
<img width="227" alt="image" src="https://github.com/user-attachments/assets/3dc9b7d7-5049-4282-9973-282e96f95c2b">

When the listner activaed, the task details returned but with not variables
<img width="818" alt="image" src="https://github.com/user-attachments/assets/743ab04c-49de-4cd4-a9dd-56e7cf3a2a0e">

I've checked in Tasklist app for the created process, and the variable is there
<img width="677" alt="image" src="https://github.com/user-attachments/assets/cd1a56f5-4690-470c-916e-af1b5014f954">

Even I've retrived the task using Tasklist REST API and the var. was returinin
<img width="629" alt="image" src="https://github.com/user-attachments/assets/b25f385f-d870-48a5-bf1c-3896271ec3c8">

I hope my description is clear enough. Please let me know if additional info. is required to figure-out this issue.

Thank you...

**Comment by asalhani** [comment]
> I've successfully set up the exporter according to the provided guide. The exporter has been enabled in the Camunda 8 Docker Compose core version (excluding Optimize and Identity).
> 
> I developed a small Spring Boot application to consume the exported records from the Redis stream. I was able to activate the listener related to the user task, named addUserTaskListener. However, I observed that the process variables are not being returned with the UserTaskRecord. The variables_ field and getVariables() method always return an empty string ("").
> 
> To ensure the process has at least one variable, I verified it within the Tasklist app. Additionally, I tested a simple gateway in the process, which successfully read the variable's value and acted upon it, confirming that the variable is recognized and respected by the Zeebe engine during runtime.
> 
> Below are some screenshot that will highlight to you the issue I descriped above:
> 
> This is how I'm initiating a new process with var: <img alt="image" width="227" src="https://private-user-images.githubusercontent.com/5410830/358854682-3dc9b7d7-5049-4282-9973-282e96f95c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTAwODEsIm5iZiI6MTcyMzkwOTc4MSwicGF0aCI6Ii81NDEwODMwLzM1ODg1NDY4Mi0zZGM5YjdkNy01MDQ5LTQyODItOTk3My0yODJlOTZmOTVjMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTU0OTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNmMWIxNmE2NTljY2JkZDRjYzhhYjdmZjlkNGU3MWQ0YzM2NDM0Mjg1NzIzNGQzZmI3MWI4ZTQzZmYyZDc2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WatVYrrXAroQnCgp3-O969Xir6lUNHBmAFXx80gP7KU">
> 
> When the listner activaed, the task details returned but with not variables <img alt="image" width="818" src="https://private-user-images.githubusercontent.com/5410830/358855067-743ab04c-49de-4cd4-a9dd-56e7cf3a2a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTAwODEsIm5iZiI6MTcyMzkwOTc4MSwicGF0aCI6Ii81NDEwODMwLzM1ODg1NTA2Ny03NDNhYjA0Yy00OWRlLTRjZDQtYTlkZC01NmU3Y2YzYTJhMGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTU0OTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2RiMzczMjc5MTYxODUzNjg3YTMzNmFlNjEzMzk5OWFiZjZkOWExMDA1NmI3OWFmZGY2OTU4MmU1ODBkMGZmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BJNERpBzoF5o0sh-lT8u478y6WD7whXlwMuB5aB80SI">
> 
> I've checked in Tasklist app for the created process, and the variable is there <img alt="image" width="677" src="https://private-user-images.githubusercontent.com/5410830/358855141-cd1a56f5-4690-470c-916e-af1b5014f954.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTAwODEsIm5iZiI6MTcyMzkwOTc4MSwicGF0aCI6Ii81NDEwODMwLzM1ODg1NTE0MS1jZDFhNTZmNS00NjkwLTQ3MGMtOTE2ZS1hZjFiNTAxNGY5NTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTU0OTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQ5NWUzMTVhNGI3ZWU4NTI3NWI0ZmZhNWIxZmMxN2RmM2VmODZkZGFmYWYxNGI3NWQ5M2JlNDAwZjU4YzMxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rdXU6TyeTmGA8PLidyBsnfqI6OCYTSbGLYc4IzjHQto">
> 
> Even I've retrived the task using Tasklist REST API and the var. was returinin <img alt="image" width="629" src="https://private-user-images.githubusercontent.com/5410830/358855270-b25f385f-d870-48a5-bf1c-3896271ec3c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTAwODEsIm5iZiI6MTcyMzkwOTc4MSwicGF0aCI6Ii81NDEwODMwLzM1ODg1NTI3MC1iMjVmMzg1Zi1kODcwLTQ4YTUtYmYxYy0zODk2MjcxZWMzYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTU0OTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTgxNjU3OWI3MzViNmY5YWY3YjFhNTU5NDRjMWJkODlhNGVkMWM1YTlhMDJiYjkxOWJlMmYyZGI2ODMwYjdkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NjXUYURnGFYC6V93vifiLZjX9Pu7rzKYSz2llNgisq4">
> 
> I hope my description is clear enough. Please let me know if additional info. is required to figure-out this issue.
> 
> Thank you...

@VonDerBeck

**Comment by VonDerBeck** [comment]
Hi @asalhani,

the behavior you observed is something you should address directly with Camunda. As far as I have observed, variables belong to the UserTaks event in case of completion events. In this case you get the completion payload as variables within the event. That's all.

I can understand the desire to access process variables in other UserTask events too. It would be nice, for example, if the variables that I define as input parameters on the UserTask always belonged to the event. Especially in case of a creation event. But that's just a wish. 

The Redis exporter only delivers the events in the form that Zeebe makes available internally. Sorry that I can't help here, but the content of the events is the responsibility of Camunda.
