### ISSUE TITLE
deploy workflow with stagin rule failures @ oss.sonatype.org

### ISSUE THREAD

**Issue by VonDerBeck** [camunda-community-hub/zeebe-redis-exporter#5]
Hi @camunda-community-hub/devrel,

I need your experience and expertise again. I try to get my deploy workflow up and running. 

Sadly I can't get rid of errors when it comes to communication with oss.sonatype.org. Last Friday absolutely nothing worked at all, from Timeouts to Bad Request I had all errors you can imagine. I suggested oss.sonatype.org unstable, maybe due to high load or whatever else. This morning everythings seems to work fine - except when it comes to closing the staging repository.

See https://github.com/camunda-community-hub/zeebe-redis-exporter/actions/runs/4041657400/jobs/6948449223

```
[INFO] Uploaded to central: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iozeebe-1528/io/zeebe/redis/zeebe-redis-connector/0.9.0/zeebe-redis-connector-0.9.0-javadoc.jar](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iozeebe-1528/io/zeebe/redis/zeebe-redis-connector/0.9.0/zeebe-redis-connector-0.9.0-javadoc.jar) (99 kB at 170 kB/s)
[INFO] Uploading to central: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iozeebe-1528/io/zeebe/redis/zeebe-redis-exporter/0.9.0/zeebe-redis-exporter-0.9.0.jar.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iozeebe-1528/io/zeebe/redis/zeebe-redis-exporter/0.9.0/zeebe-redis-exporter-0.9.0.jar.asc)
[INFO] Uploaded to central: [https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iozeebe-1528/io/zeebe/redis/zeebe-redis-exporter/0.9.0/zeebe-redis-exporter-0.9.0.jar.asc](https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iozeebe-1528/io/zeebe/redis/zeebe-redis-exporter/0.9.0/zeebe-redis-exporter-0.9.0.jar.asc) (659 B at 3.9 kB/s)
[INFO]  * Upload of locally staged artifacts finished.
[INFO]  * Closing staging repository with ID "iozeebe-1528".

Waiting for operation to complete...
............................................................................................
Warning:  TIMEOUT after 302.7 s

Error:  Rule failure while trying to close staging repository with ID "iozeebe-1528".
Error:  
Error:  Nexus Staging Rules Failure Report
Error:  ==================================
Error:  
Error:  
Error:  Cleaning up local stage directory after a Rule failure during close of staging repositories: []
Error:   * Deleting context 771b23290bd13e.properties
Error:  Cleaning up remote stage repositories after a Rule failure during close of staging repositories: []
Error:   * Dropping failed staging repository with ID "iozeebe-1528" (Rule failure during close of staging repositories: []).

Waiting for operation to complete...
.........

Error:  Remote staging finished with a failure: Staging rules failure!
```

I already checked if a change of the `maven-url` to `s01.oss.sonatype.org` makes a difference, but this failes immediately.

Do you have any hints what I'm missing? Is there something you must do in order to prepare sonatype.org for the onboarding of this repository?

Any help is welcome.

Thanks in advance,
Gunnar

**Comment by berndruecker** [comment]
Huh - wired. Unfortunately I have no spontaneous idea :-( Maybe we can retry later today and if that does not work go into the trenches and google our way forward? I think we might also be able to raise an issue with Sonatype

**Comment by VonDerBeck** [comment]
Thanks @berndruecker for your honest answer. So I will try the ancient classic solution: reboot in case of errors. ;-)

**Comment by VonDerBeck** [comment]
@berndruecker: seems like Sonatype has some challenges with "unexpected" workload, we're not the only ones having issues since the last weekend. See e.g. https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-8825. Thanks for creating [MVNCENTRAL-7816](https://issues.sonatype.org/browse/MVNCENTRAL-7816) 👍

**Comment by VonDerBeck** [comment]
Hi @berndruecker, @camunda-community-hub/devrel,

looks like Sonatype is up and running again. My deploy workflow has been successful :-)

**Comment by berndruecker** [comment]
Great - I released it to Maven Central (this currently is a manual click - we discuss to get rid of it in https://github.com/camunda-community-hub/community-action-maven-release/issues/48)
