### ISSUE TITLE
Release of version 0.9.1

### ISSUE THREAD

**Issue by VonDerBeck** [camunda-community-hub/zeebe-redis-exporter#9]
@camunda-community-hub/devrel: please release version 0.9.1

**Comment by berndruecker** [comment]
Hi @VonDerBeck - I see that you updated the parent pom. We actually fixed some things there - so we could also enable auto releases. I double checked and haven't found anything staged from you to release - so I think it worked and your artifact got directly released. Let me know if not!

That means, from now on you can simply release on your own 🎉
